name: Lint and Test

on:
  push: 
    
  pull_request:
  workflow_dispatch:


jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.x"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@v1.5.4
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
        env:
          GOBIN: /home/runner/go/bin
        shell: bash

      - name: Generate protobuf
        run: |
          make protoc

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: ./
          skip-cache: true
          skip-save-cache: true
          args: --timeout=99m

      - name: Run tests
        run: |
          make test
